version: "3.7"
services:
  db:
    image: mysql:8.0.15
    container_name: ss-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ss
      MYSQL_USER: ss
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
