spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/ss
    username: ss
    password: mypassword
    driverClassName: com.mysql.cj.jdbc.Driver
    schema: classpath:schema.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database: MYSQL
  mvc:
    hiddenmethod:
      filter:
        enabled: true
