spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ttdd
    username: ttdd
    password: password
    initialization-mode: always
    schema: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
  mvc:
    hiddenmethod:
      filter:
        enabled: true