version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  heroku_deploy:
    jobs:
      - build
      - start_deploy:
          type: approval
          requires:
            - build
      - heroku/deploy-via-git:
          requires:
            - start_deploy

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: mysql:8.0.15
        environment:
          MYSQL_USER: ss
          MYSQL_DATABASE: ss
          MYSQL_PASSWORD: mypassword
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 20`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Run unit tests
          command: ./gradlew test
